name: "Transifex Push"

on:
  push:
    branches:
      - "main"

jobs:
  transifex_push:
    name: "Transifex Push"
    uses: "glpi-project/plugin-translation-workflows/.github/workflows/transifex_push.yml@v1"
    with:
      branch: "main"
    secrets:
      tx_token: "${{ secrets.TRANSIFEX_TOKEN }}"
